### ISSUE TITLE
JustRemark

### ISSUE THREAD

**Issue by SophiToyber** [AnimaAllegra/First-repository#1]
https://github.com/AnimaAllegra/First-repository/blob/398c2c382574d733b0429b48e887428ae612e138/here%20tasks%201/zd3.java#L5

for best code style use `a-=5` instead of `a=a-5`

**Comment by AnimaAllegra** [comment]
https://github.com/AnimaAllegra/First-repository/blob/master/here%20tasks%201/zd3.java
