### ISSUE TITLE
JustRemark - zd5.java

### ISSUE THREAD

**Issue by SophiToyber** [AnimaAllegra/First-repository#2]
https://github.com/AnimaAllegra/First-repository/blob/398c2c382574d733b0429b48e887428ae612e138/here%20tasks%201/zd5.java#L6

for this task it is better to use `do ... while` or `while`

**Comment by AnimaAllegra** [comment]
https://github.com/AnimaAllegra/First-repository/blob/master/here%20tasks%201/zd5.java

**Comment by AnimaAllegra** [comment]
https://github.com/AnimaAllegra/First-repository/blob/master/here%20tasks%201/zd4.java
