### ISSUE TITLE
JustRemark - zd6.java

### ISSUE THREAD

**Issue by SophiToyber** [AnimaAllegra/First-repository#3]
https://github.com/AnimaAllegra/First-repository/blob/398c2c382574d733b0429b48e887428ae612e138/here%20tasks%201/zd6.java#L6
Man, is an ugly code. Do you want to learn **quality** programming?
If yes, **fix this code using the comments in the previous issues**.

**Comment by AnimaAllegra** [comment]
https://github.com/AnimaAllegra/First-repository/blob/master/here%20tasks%201/zd6.java
