### ISSUE TITLE
Answer to the question

### ISSUE THREAD

**Issue by SophiToyber** [AnimaAllegra/First-repository#4]
https://github.com/AnimaAllegra/First-repository/blob/bacd978551d831365dd93b4951c10a5e4e48cade/here%20tasks%20for%2011.05.2020/task2.java#L21
Это обычный вывод массива, но начиная с конца 
А почему там отнимают 1:
Допустим, размер твоего массива **array.length() -> 10** , поскольку елементы начинаются с `0`, то последним елементом массива будет `9`.
И это значит, что если ты будешь брать просто `array.length()`, то программа будет пытаться получить доступ к несуществующему елементу `arr[10]`.
Именно по этому мы отнимаем единицу

**Comment by AnimaAllegra** [comment]
Thank you!
