### ISSUE TITLE
JustRemark #2

### ISSUE THREAD

**Issue by SophiToyber** [AnimaAllegra/First-repository#5]
https://github.com/AnimaAllegra/First-repository/blob/3ede7ffe170dccb8f9a46332861230c64c33b421/another%20tasks%20for%2011.05.2020/Main.java#L15

What are you doing at this step?
The condition says to replace an element with an odd index by zero.
And here you assign to all elements except the first one zero.

So, change something ;)

**Comment by AnimaAllegra** [comment]
https://github.com/AnimaAllegra/First-repository/blob/master/another%20tasks%20for%2011.05.2020/Main.java

Thanks:)
I was so tired
